services:
  - type: web
    name: theadstudio-backend
    env: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg nodejs npm chromium && pip install -r requirements.txt && cd remotion && npm install"
    startCommand: "gunicorn ad_generator_backend:app --timeout 300 --workers 1"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REMOTION_BROWSER_EXECUTABLE
        value: /usr/bin/chromium
