import React from 'react';
import {AbsoluteFill, Audio, Img, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {TransitionSeries, linearTiming} from '@remotion/transitions';
import {fade} from '@remotion/transitions/fade';
import {z} from 'zod';
import {CtaEnd} from './CtaEnd';
import {getAudioDurationSeconds} from './audio-duration';
import {
	ABSOLUTE_MAX_DURATION_SECONDS,
	ABSOLUTE_MIN_DURATION_SECONDS,
	CTA_SECONDS,
	FONT_FAMILY,
	FPS,
	GOLD,
	MIN_SCALED_CTA_SECONDS,
	TRANSITION_SECONDS,
} from './constants';

// A real talking-presenter format built entirely from free/local pieces: one
// avatar portrait held on screen for a real voiceover track (generated by
// remotion/scripts/generate_voiceover.py - gTTS/Piper/espeak-ng, no paid
// API), with synced lower-third captions and a speaking indicator. This is
// NOT lip-synced video (that needs a paid avatar renderer like Creatify's
// AI Avatar mode in the web UI) - same honesty as TestimonialAd, but this
// one has a real spoken voiceover under it instead of silent review cards.
export const avatarUGCSchema = z.object({
	avatarImage: z.string(),
	avatarBlinkImage: z.string().optional(), // optional second frame for a subtle blink crossfade
	captions: z.array(z.string()), // spoken-line captions, evenly synced across the voiceover
	voiceover: z.string(), // the actual spoken audio track
	music: z.string().optional(), // optional quiet background bed, mixed low under the voiceover
	cta: z.string(),
	link: z.string(),
	logoPath: z.string().optional(),
	durationSeconds: z.number().optional(),
	totalFrames: z.number().optional(),
});

export type AvatarUGCProps = z.infer<typeof avatarUGCSchema>;

const secondsToFrames = (seconds: number) => Math.round(seconds * FPS);

export const calculateAvatarUGCMetadata = async ({props}: {props: AvatarUGCProps}) => {
	let totalSeconds: number;
	if (props.durationSeconds) {
		totalSeconds = Math.max(
			ABSOLUTE_MIN_DURATION_SECONDS,
			Math.min(props.durationSeconds, ABSOLUTE_MAX_DURATION_SECONDS)
		);
	} else {
		// Driven by the voiceover's own length (not a music track) - a UGC
		// script naturally runs shorter or longer than the 25-30s photo-ad
		// default, so just give it what it needs plus room for the CTA.
		const voiceoverDuration = await getAudioDurationSeconds(props.voiceover);
		totalSeconds = Math.max(
			ABSOLUTE_MIN_DURATION_SECONDS,
			Math.min(voiceoverDuration + CTA_SECONDS, ABSOLUTE_MAX_DURATION_SECONDS)
		);
	}
	return {durationInFrames: secondsToFrames(totalSeconds), props: {...props, totalFrames: secondsToFrames(totalSeconds)}};
};

const BLINK_PERIOD_FRAMES = 95;
const BLINK_HOLD_FRAMES = 5;

// A small animated bar meter next to the caption, standing in for a
// "speaking now" indicator since there's no real lip-sync to show.
const SpeakingBars: React.FC = () => {
	const frame = useCurrentFrame();
	return (
		<div style={{display: 'flex', alignItems: 'flex-end', gap: 6, height: 28}}>
			{[0, 1, 2, 3].map((i) => {
				const phase = frame / 4 + i * 1.7;
				const h = 8 + (Math.sin(phase) * 0.5 + 0.5) * 20;
				return <div key={i} style={{width: 6, height: h, borderRadius: 3, background: GOLD}} />;
			})}
		</div>
	);
};

const AvatarScene: React.FC<{
	avatarImage: string;
	avatarBlinkImage?: string;
	captions: string[];
}> = ({avatarImage, avatarBlinkImage, captions}) => {
	const frame = useCurrentFrame();
	const {durationInFrames} = useVideoConfig();

	// Slow "breathing" zoom for the whole scene - a portrait held on camera,
	// not panning across a photo like KenBurnsAd, so it eases in and back out
	// instead of zooming continuously in one direction.
	const scale = 1 + 0.05 * (0.5 - 0.5 * Math.cos((frame / Math.max(1, durationInFrames)) * Math.PI * 2));

	// Occasional blink: crossfade to the blink frame for a few frames every cycle.
	const cyclePos = frame % BLINK_PERIOD_FRAMES;
	const blinkOpacity = avatarBlinkImage
		? interpolate(cyclePos, [0, BLINK_HOLD_FRAMES / 2, BLINK_HOLD_FRAMES, BLINK_HOLD_FRAMES + 6], [0, 1, 1, 0], {
				extrapolateLeft: 'clamp',
				extrapolateRight: 'clamp',
			})
		: 0;

	const beatCount = Math.max(1, captions.length);
	const perBeat = Math.max(1, Math.floor(durationInFrames / beatCount));
	const activeIndex = Math.min(beatCount - 1, Math.floor(frame / perBeat));
	const currentCaption = captions[activeIndex] ?? '';
	const beatFrame = frame - activeIndex * perBeat;
	const captionOpacity = interpolate(beatFrame, [0, 12], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
	const captionY = interpolate(beatFrame, [0, 12], [16, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});

	return (
		<AbsoluteFill style={{background: '#000', overflow: 'hidden'}}>
			<Img
				src={avatarImage}
				style={{
					position: 'absolute',
					inset: 0,
					width: '100%',
					height: '100%',
					objectFit: 'cover',
					transform: `scale(${scale})`,
				}}
			/>
			{avatarBlinkImage ? (
				<Img
					src={avatarBlinkImage}
					style={{
						position: 'absolute',
						inset: 0,
						width: '100%',
						height: '100%',
						objectFit: 'cover',
						transform: `scale(${scale})`,
						opacity: blinkOpacity,
					}}
				/>
			) : null}
			<div
				style={{
					position: 'absolute',
					inset: 0,
					background:
						'linear-gradient(180deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0) 22%, rgba(0,0,0,0) 58%, rgba(0,0,0,0.8) 100%)',
				}}
			/>
			<div
				style={{
					position: 'absolute',
					bottom: 64,
					left: 50,
					right: 50,
					display: 'flex',
					flexDirection: 'column',
					alignItems: 'center',
					gap: 18,
					opacity: captionOpacity,
					transform: `translateY(${captionY}px)`,
				}}
			>
				<SpeakingBars />
				{currentCaption ? (
					<div style={{background: 'rgba(0,0,0,0.55)', borderLeft: `6px solid ${GOLD}`, padding: '20px 30px', borderRadius: 6}}>
						<span
							style={{
								color: 'white',
								fontFamily: FONT_FAMILY,
								fontWeight: 700,
								fontSize: 38,
								textAlign: 'center',
							}}
						>
							{currentCaption}
						</span>
					</div>
				) : null}
			</div>
		</AbsoluteFill>
	);
};

export const AvatarUGCAd: React.FC<AvatarUGCProps> = ({
	avatarImage,
	avatarBlinkImage,
	captions,
	voiceover,
	music,
	cta,
	link,
	logoPath,
	totalFrames,
}) => {
	const ctaFrames = secondsToFrames(MIN_SCALED_CTA_SECONDS);
	const transitionFrames = secondsToFrames(TRANSITION_SECONDS);
	const effectiveTotalFrames = totalFrames ?? secondsToFrames(ABSOLUTE_MAX_DURATION_SECONDS);
	const sceneFrames = Math.max(1, effectiveTotalFrames - ctaFrames + transitionFrames);

	return (
		<>
			<Audio src={voiceover} />
			{music ? <Audio src={music} volume={0.12} /> : null}
			<TransitionSeries>
				<TransitionSeries.Sequence durationInFrames={sceneFrames}>
					<AvatarScene avatarImage={avatarImage} avatarBlinkImage={avatarBlinkImage} captions={captions} />
				</TransitionSeries.Sequence>
				<TransitionSeries.Transition presentation={fade()} timing={linearTiming({durationInFrames: transitionFrames})} />
				<TransitionSeries.Sequence durationInFrames={ctaFrames}>
					<CtaEnd cta={cta} link={link} logoPath={logoPath} />
				</TransitionSeries.Sequence>
			</TransitionSeries>
		</>
	);
};
