import React from 'react';
import {AbsoluteFill, Audio, Img, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {TransitionSeries, linearTiming} from '@remotion/transitions';
import {fade} from '@remotion/transitions/fade';
import {z} from 'zod';
import {CtaEnd} from './CtaEnd';
import {getAudioDurationSeconds} from './audio-duration';
import {
	ABSOLUTE_MAX_DURATION_SECONDS,
	ABSOLUTE_MIN_DURATION_SECONDS,
	CTA_SECONDS,
	FONT_FAMILY,
	FPS,
	GOLD,
	MIN_SCALED_CTA_SECONDS,
	TRANSITION_SECONDS,
} from './constants';

// A real talking-presenter format built entirely from free/local pieces: one
// or more real avatar photos (a genuine person, not a rendered avatar - see
// demo/avatar-ugc for an example using two real photos of the same presenter)
// cut between per caption beat, playing under a real voiceover track
// generated by remotion/scripts/generate_voiceover.py (gTTS/Piper/espeak-ng,
// no paid API). This is NOT lip-synced video (that needs a paid avatar
// renderer like Creatify's AI Avatar mode in the web UI) - same honesty as
// TestimonialAd, but this one has a real spoken voiceover under real photos
// instead of silent review cards.
export const avatarUGCSchema = z.object({
	avatarImages: z.array(z.string()), // one or more presenter photos, one per caption beat
	captions: z.array(z.string()), // spoken-line captions, one per avatarImages entry
	voiceover: z.string(), // the actual spoken audio track
	music: z.string().optional(), // optional quiet background bed, mixed low under the voiceover
	cta: z.string(),
	link: z.string(),
	logoPath: z.string().optional(),
	durationSeconds: z.number().optional(),
	totalFrames: z.number().optional(),
});

export type AvatarUGCProps = z.infer<typeof avatarUGCSchema>;

const secondsToFrames = (seconds: number) => Math.round(seconds * FPS);

export const calculateAvatarUGCMetadata = async ({props}: {props: AvatarUGCProps}) => {
	let totalSeconds: number;
	if (props.durationSeconds) {
		totalSeconds = Math.max(
			ABSOLUTE_MIN_DURATION_SECONDS,
			Math.min(props.durationSeconds, ABSOLUTE_MAX_DURATION_SECONDS)
		);
	} else {
		// Driven by the voiceover's own length (not a music track) - a UGC
		// script naturally runs shorter or longer than the 25-30s photo-ad
		// default, so just give it what it needs plus room for the CTA.
		const voiceoverDuration = await getAudioDurationSeconds(props.voiceover);
		totalSeconds = Math.max(
			ABSOLUTE_MIN_DURATION_SECONDS,
			Math.min(voiceoverDuration + CTA_SECONDS, ABSOLUTE_MAX_DURATION_SECONDS)
		);
	}
	return {durationInFrames: secondsToFrames(totalSeconds), props: {...props, totalFrames: secondsToFrames(totalSeconds)}};
};

// A small animated bar meter next to the caption, standing in for a
// "speaking now" indicator since there's no real lip-sync to show.
const SpeakingBars: React.FC = () => {
	const frame = useCurrentFrame();
	return (
		<div style={{display: 'flex', alignItems: 'flex-end', gap: 6, height: 28}}>
			{[0, 1, 2, 3].map((i) => {
				const phase = frame / 4 + i * 1.7;
				const h = 8 + (Math.sin(phase) * 0.5 + 0.5) * 20;
				return <div key={i} style={{width: 6, height: h, borderRadius: 3, background: GOLD}} />;
			})}
		</div>
	);
};

const AvatarBeat: React.FC<{src: string; caption?: string}> = ({src, caption}) => {
	const frame = useCurrentFrame();
	const {durationInFrames} = useVideoConfig();

	// Slow "breathing" zoom for the whole beat - a portrait held on camera,
	// easing in and back out rather than zooming continuously in one
	// direction like KenBurnsAd does across a landscape product photo.
	const scale = 1 + 0.05 * (0.5 - 0.5 * Math.cos((frame / Math.max(1, durationInFrames)) * Math.PI * 2));

	const captionOpacity = interpolate(frame, [6, 22], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
	const captionY = interpolate(frame, [6, 22], [16, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});

	return (
		<AbsoluteFill style={{background: '#000', overflow: 'hidden'}}>
			<Img
				src={src}
				style={{
					position: 'absolute',
					inset: 0,
					width: '100%',
					height: '100%',
					objectFit: 'cover',
					transform: `scale(${scale})`,
				}}
			/>
			<div
				style={{
					position: 'absolute',
					inset: 0,
					background:
						'linear-gradient(180deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0) 22%, rgba(0,0,0,0) 58%, rgba(0,0,0,0.8) 100%)',
				}}
			/>
			<div
				style={{
					position: 'absolute',
					bottom: 64,
					left: 50,
					right: 50,
					display: 'flex',
					flexDirection: 'column',
					alignItems: 'center',
					gap: 18,
					opacity: captionOpacity,
					transform: `translateY(${captionY}px)`,
				}}
			>
				<SpeakingBars />
				{caption ? (
					<div style={{background: 'rgba(0,0,0,0.55)', borderLeft: `6px solid ${GOLD}`, padding: '20px 30px', borderRadius: 6}}>
						<span
							style={{
								color: 'white',
								fontFamily: FONT_FAMILY,
								fontWeight: 700,
								fontSize: 38,
								textAlign: 'center',
							}}
						>
							{caption}
						</span>
					</div>
				) : null}
			</div>
		</AbsoluteFill>
	);
};

type Segment =
	| {kind: 'avatar'; frames: number; src: string; caption?: string}
	| {kind: 'cta'; frames: number; cta: string; link: string; logoPath?: string};

export const AvatarUGCAd: React.FC<AvatarUGCProps> = ({
	avatarImages,
	captions,
	voiceover,
	music,
	cta,
	link,
	logoPath,
	totalFrames,
}) => {
	const ctaFrames = secondsToFrames(MIN_SCALED_CTA_SECONDS);
	const transitionFrames = secondsToFrames(TRANSITION_SECONDS);
	const effectiveTotalFrames = totalFrames ?? secondsToFrames(ABSOLUTE_MAX_DURATION_SECONDS);

	const beatBudgetFrames = Math.max(1, effectiveTotalFrames - ctaFrames);
	const beatCount = Math.max(1, avatarImages.length);
	const framesPerBeat = Math.max(1, Math.floor(beatBudgetFrames / beatCount));

	const segments: Segment[] = avatarImages.map((src, i) => ({
		kind: 'avatar',
		frames: framesPerBeat,
		src,
		caption: captions[i],
	}));
	segments.push({kind: 'cta', frames: ctaFrames, cta, link, logoPath});

	const transitionsCount = Math.max(0, segments.length - 1);
	const rawTotal = segments.reduce((sum, s) => sum + s.frames, 0);
	const deficit = effectiveTotalFrames - (rawTotal - transitionsCount * transitionFrames);
	if (deficit > 0) segments[segments.length - 1].frames += deficit;

	return (
		<>
			<Audio src={voiceover} />
			{music ? <Audio src={music} volume={0.12} /> : null}
			<TransitionSeries>
				{segments.map((segment, i) => (
					<React.Fragment key={i}>
						<TransitionSeries.Sequence durationInFrames={segment.frames}>
							{segment.kind === 'avatar' ? <AvatarBeat src={segment.src} caption={segment.caption} /> : null}
							{segment.kind === 'cta' ? <CtaEnd cta={segment.cta} link={segment.link} logoPath={segment.logoPath} /> : null}
						</TransitionSeries.Sequence>
						{i < segments.length - 1 ? (
							<TransitionSeries.Transition presentation={fade()} timing={linearTiming({durationInFrames: transitionFrames})} />
						) : null}
					</React.Fragment>
				))}
			</TransitionSeries>
		</>
	);
};
