import React from 'react';
import {AbsoluteFill, Audio, Img, OffthreadVideo, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {TransitionSeries, linearTiming} from '@remotion/transitions';
import {fade} from '@remotion/transitions/fade';
import {z} from 'zod';
import {CtaEnd} from './CtaEnd';
import {getAudioDurationSeconds} from './audio-duration';
import {
	ABSOLUTE_MAX_DURATION_SECONDS,
	ABSOLUTE_MIN_DURATION_SECONDS,
	CTA_SECONDS,
	FONT_FAMILY,
	FPS,
	GOLD,
	MIN_SCALED_CTA_SECONDS,
	TRANSITION_SECONDS,
} from './constants';

// A real talking-presenter format built entirely from free/local pieces: an
// ordered list of "beats", each pairing one image (or, optionally, a
// pre-rendered lip-synced video clip - see remotion/scripts/lipsync_wav2lip/
// README, non-commercial use only) with the exact line being said over it -
// real presenter photos ('avatar' beats, with a "speaking" bar indicator)
// interleaved with supporting product cutaways ('feature' beats, no
// speaking indicator) so the visual always matches the specific claim in
// that caption, the way a real edited UGC video cuts to B-roll while the
// voiceover continues. Plays under a real voiceover track generated by
// remotion/scripts/generate_voiceover.py (gTTS/Piper/espeak-ng, no paid
// API). Without a `video` on a beat, this is not lip-synced (same honesty
// as TestimonialAd) - a real spoken voiceover plays under a real photo
// instead of silent review cards.
export const avatarUGCSchema = z.object({
	beats: z.array(
		z.object({
			image: z.string().optional(), // a presenter photo or a supporting product shot (poster/fallback when `video` is set)
			video: z.string().optional(), // optional pre-rendered lip-synced clip (muted - audio comes from the shared `voiceover` track) for this beat instead of a static image
			caption: z.string(), // the exact line spoken while this image/video is on screen
			kind: z.enum(['avatar', 'feature']).optional(), // 'avatar' (default): presenter shot, shows the speaking-bar indicator. 'feature': product/B-roll cutaway, no speaking indicator.
			durationSeconds: z.number().optional(), // exact on-screen time for this beat (e.g. matched to its own voiceover line); beats without this split the remaining time evenly
		})
	),
	voiceover: z.string(), // the actual spoken audio track
	music: z.string().optional(), // optional quiet background bed, mixed low under the voiceover
	cta: z.string(),
	link: z.string(),
	logoPath: z.string().optional(),
	durationSeconds: z.number().optional(),
	totalFrames: z.number().optional(),
});

export type AvatarUGCProps = z.infer<typeof avatarUGCSchema>;

const secondsToFrames = (seconds: number) => Math.round(seconds * FPS);

export const calculateAvatarUGCMetadata = async ({props}: {props: AvatarUGCProps}) => {
	let totalSeconds: number;
	if (props.durationSeconds) {
		totalSeconds = Math.max(
			ABSOLUTE_MIN_DURATION_SECONDS,
			Math.min(props.durationSeconds, ABSOLUTE_MAX_DURATION_SECONDS)
		);
	} else {
		// Driven by the voiceover's own length (not a music track) - a UGC
		// script naturally runs shorter or longer than the 25-30s photo-ad
		// default, so just give it what it needs plus room for the CTA.
		const voiceoverDuration = await getAudioDurationSeconds(props.voiceover);
		totalSeconds = Math.max(
			ABSOLUTE_MIN_DURATION_SECONDS,
			Math.min(voiceoverDuration + CTA_SECONDS, ABSOLUTE_MAX_DURATION_SECONDS)
		);
	}
	return {durationInFrames: secondsToFrames(totalSeconds), props: {...props, totalFrames: secondsToFrames(totalSeconds)}};
};

// A small animated bar meter next to the caption, standing in for a
// "speaking now" indicator on presenter beats without a lip-synced video.
const SpeakingBars: React.FC = () => {
	const frame = useCurrentFrame();
	return (
		<div style={{display: 'flex', alignItems: 'flex-end', gap: 6, height: 28}}>
			{[0, 1, 2, 3].map((i) => {
				const phase = frame / 4 + i * 1.7;
				const h = 8 + (Math.sin(phase) * 0.5 + 0.5) * 20;
				return <div key={i} style={{width: 6, height: h, borderRadius: 3, background: GOLD}} />;
			})}
		</div>
	);
};

const AvatarBeat: React.FC<{src: string; isVideo: boolean; caption?: string; showSpeakingBars: boolean}> = ({
	src,
	isVideo,
	caption,
	showSpeakingBars,
}) => {
	const frame = useCurrentFrame();
	const {durationInFrames} = useVideoConfig();

	// Slow "breathing" zoom for the whole beat, easing in and back out rather
	// than zooming continuously in one direction like KenBurnsAd does across
	// a landscape product photo - reads more like a held shot than a pan.
	const scale = 1 + 0.05 * (0.5 - 0.5 * Math.cos((frame / Math.max(1, durationInFrames)) * Math.PI * 2));

	const captionOpacity = interpolate(frame, [6, 22], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
	const captionY = interpolate(frame, [6, 22], [16, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});

	return (
		<AbsoluteFill style={{background: '#000', overflow: 'hidden'}}>
			{isVideo ? (
				<OffthreadVideo
					src={src}
					muted
					style={{
						position: 'absolute',
						inset: 0,
						width: '100%',
						height: '100%',
						objectFit: 'cover',
						transform: `scale(${scale})`,
					}}
				/>
			) : (
				<Img
					src={src}
					style={{
						position: 'absolute',
						inset: 0,
						width: '100%',
						height: '100%',
						objectFit: 'cover',
						transform: `scale(${scale})`,
					}}
				/>
			)}
			<div
				style={{
					position: 'absolute',
					inset: 0,
					background:
						'linear-gradient(180deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0) 22%, rgba(0,0,0,0) 58%, rgba(0,0,0,0.8) 100%)',
				}}
			/>
			<div
				style={{
					position: 'absolute',
					bottom: 64,
					left: 50,
					right: 50,
					display: 'flex',
					flexDirection: 'column',
					alignItems: 'center',
					gap: 18,
					opacity: captionOpacity,
					transform: `translateY(${captionY}px)`,
				}}
			>
				{showSpeakingBars ? <SpeakingBars /> : null}
				{caption ? (
					<div style={{background: 'rgba(0,0,0,0.55)', borderLeft: `6px solid ${GOLD}`, padding: '20px 30px', borderRadius: 6}}>
						<span
							style={{
								color: 'white',
								fontFamily: FONT_FAMILY,
								fontWeight: 700,
								fontSize: 38,
								textAlign: 'center',
							}}
						>
							{caption}
						</span>
					</div>
				) : null}
			</div>
		</AbsoluteFill>
	);
};

type Segment =
	| {kind: 'beat'; frames: number; src: string; isVideo: boolean; caption?: string; showSpeakingBars: boolean}
	| {kind: 'cta'; frames: number; cta: string; link: string; logoPath?: string};

export const AvatarUGCAd: React.FC<AvatarUGCProps> = ({beats, voiceover, music, cta, link, logoPath, totalFrames}) => {
	const ctaFrames = secondsToFrames(MIN_SCALED_CTA_SECONDS);
	const transitionFrames = secondsToFrames(TRANSITION_SECONDS);
	const effectiveTotalFrames = totalFrames ?? secondsToFrames(ABSOLUTE_MAX_DURATION_SECONDS);
	const beatBudgetFrames = Math.max(1, effectiveTotalFrames - ctaFrames);

	// Beats with an explicit durationSeconds (e.g. matched to their own
	// voiceover line) get exactly that many frames; the rest split whatever
	// budget is left evenly, same as the original even-split behavior.
	const explicitFrames = beats.map((b) => (b.durationSeconds != null ? secondsToFrames(b.durationSeconds) : null));
	const explicitTotal = explicitFrames.reduce((sum: number, f) => sum + (f ?? 0), 0);
	const beatsWithoutExplicit = explicitFrames.filter((f) => f == null).length;
	const remainingBudget = Math.max(0, beatBudgetFrames - explicitTotal);
	const fallbackFramesPerBeat = beatsWithoutExplicit > 0 ? Math.max(1, Math.floor(remainingBudget / beatsWithoutExplicit)) : 0;

	const segments: Segment[] = beats.map((beat, i) => ({
		kind: 'beat',
		frames: explicitFrames[i] ?? fallbackFramesPerBeat,
		src: beat.video || beat.image || '',
		isVideo: Boolean(beat.video),
		caption: beat.caption,
		showSpeakingBars: (beat.kind ?? 'avatar') === 'avatar',
	}));
	segments.push({kind: 'cta', frames: ctaFrames, cta, link, logoPath});

	const transitionsCount = Math.max(0, segments.length - 1);
	const rawTotal = segments.reduce((sum, s) => sum + s.frames, 0);
	const deficit = effectiveTotalFrames - (rawTotal - transitionsCount * transitionFrames);
	if (deficit > 0) segments[segments.length - 1].frames += deficit;

	return (
		<>
			<Audio src={voiceover} />
			{music ? <Audio src={music} volume={0.12} /> : null}
			<TransitionSeries>
				{segments.map((segment, i) => (
					<React.Fragment key={i}>
						<TransitionSeries.Sequence durationInFrames={segment.frames}>
							{segment.kind === 'beat' ? (
								<AvatarBeat
									src={segment.src}
									isVideo={segment.isVideo}
									caption={segment.caption}
									showSpeakingBars={segment.showSpeakingBars}
								/>
							) : null}
							{segment.kind === 'cta' ? <CtaEnd cta={segment.cta} link={segment.link} logoPath={segment.logoPath} /> : null}
						</TransitionSeries.Sequence>
						{i < segments.length - 1 ? (
							<TransitionSeries.Transition presentation={fade()} timing={linearTiming({durationInFrames: transitionFrames})} />
						) : null}
					</React.Fragment>
				))}
			</TransitionSeries>
		</>
	);
};
